// Generated by CoffeeScript 1.9.1
(function() {
  var Button, arr, clickTheAtPlusToStartTheRobot, countSum, index, initButtons, resetBubble, resetIfLeaveTheApb;

  arr = new Array();

  arr = [0, 1, 2, 3, 4];

  index = 0;

  Button = (function() {
    Button.prototype.buttons = [];

    Button.prototype.disableOtherButtonsExcept = function(thisButton) {
      var button, i, len, ref, results;
      ref = Button.prototype.buttons;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        button = ref[i];
        if (button !== thisButton && button.state === "enable") {
          button.state = "disable";
          results.push(button.dom.css("background-color", "gray"));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    Button.prototype.enableButtonsAfterDone = function() {
      var button, i, len, ref, results;
      ref = Button.prototype.buttons;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        button = ref[i];
        if (button.state === "disable") {
          button.state = "enable";
          results.push(button.dom.css("background-color", "rgb(48, 63, 159)"));
        } else {
          results.push(void 0);
        }
      }
      return results;
    };

    Button.prototype.clickAllButtonsInOrder = function(index) {
      var btns, current;
      if (index >= 5) {
        return;
      }
      btns = Button.prototype.buttons;
      current = arr[index];
      return btns[current].executeClickEvent();
    };

    Button.prototype.executeClickEvent = function() {
      this.dom.find(".adder").css("display", "block").text("...");
      this.state = "waiting";
      Button.prototype.disableOtherButtonsExcept(this);
      return this.getRandomNumberFromTheServer();
    };

    Button.prototype.getRandomNumberFromTheServer = function() {
      return $.get("/", (function(_this) {
        return function(data) {
          if (_this.state === "waiting") {
            _this.dom.find(".adder").text(data);
            _this.state = "done";
            _this.dom.css("background-color", "gray");
            Button.prototype.ifAllButtonsAreDoneClickTheBubble();
            Button.prototype.enableButtonsAfterDone();
            return Button.prototype.clickAllButtonsInOrder(index++);
          }
        };
      })(this));
    };

    Button.prototype.ifAllButtonsAreDoneClickTheBubble = function() {
      var bubble, button, i, len, ref;
      ref = Button.prototype.buttons;
      for (i = 0, len = ref.length; i < len; i++) {
        button = ref[i];
        if (button.state !== "done") {
          return;
        }
      }
      bubble = $("#info-bar");
      bubble.attr("enable", "true");
      bubble.css("background-color", "gray");
      return bubble.find("#sum").text(countSum());
    };

    function Button(dom1) {
      this.dom = dom1;
      this.state = "enable";
      Button.prototype.buttons.push(this);
    }

    Button.prototype.resetAllButtons = function() {
      var button, i, len, ref, results;
      ref = Button.prototype.buttons;
      results = [];
      for (i = 0, len = ref.length; i < len; i++) {
        button = ref[i];
        button.state = "enable";
        button.dom.css("background-color", "rgb(48, 63, 159)");
        results.push(button.dom.find(".adder").css("display", "none").text(""));
      }
      return results;
    };

    return Button;

  })();

  $(function() {
    initButtons();
    clickTheAtPlusToStartTheRobot();
    return resetIfLeaveTheApb();
  });

  initButtons = function() {
    var button, dom, i, len, ref, results;
    ref = $("#control-ring li");
    results = [];
    for (i = 0, len = ref.length; i < len; i++) {
      dom = ref[i];
      results.push(button = new Button($(dom)));
    }
    return results;
  };

  clickTheAtPlusToStartTheRobot = function() {
    return $(".apb").click((function(_this) {
      return function() {
        if (index !== 0) {
          return;
        }
        return Button.prototype.clickAllButtonsInOrder(index);
      };
    })(this));
  };

  countSum = function() {
    var dom, i, len, number, ref, result;
    result = 0;
    ref = $('#control-ring li');
    for (i = 0, len = ref.length; i < len; i++) {
      dom = ref[i];
      number = $(dom).find('.adder').text();
      result += parseInt(number);
    }
    return result;
  };

  resetIfLeaveTheApb = function() {
    return $('#at-plus-container').on('mouseleave', function() {
      Button.prototype.resetAllButtons();
      resetBubble();
      return index = 0;
    });
  };

  resetBubble = function() {
    var bubble;
    bubble = $('#info-bar');
    bubble.find('span').text("");
    return bubble.css('background-color', 'gray');
  };

}).call(this);
