// Generated by LiveScript 1.3.1
(function(){
  var init, addNumberToAllButtonClick, disableAllOtherButton, pullRequerstToServerAndShowNumber, calculate, enableAllOtherButton, allButtonIsDone, addResultToBubble, addResetToApbMouseleave, Robot, addSequenceClickToApb;
  $(function(){
    init();
    addNumberToAllButtonClick();
    addResetToApbMouseleave();
    return addSequenceClickToApb();
  });
  init = function(){
    var i$, ref$, len$, btn;
    for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
      btn = ref$[i$];
      btn.status = 'enable';
      $(btn).removeClass('disabled done').addClass('enable');
      $(btn).find('.unread').text('...').addClass('unseen');
    }
    $('#info-bar').removeClass('enable').addClass('disabled').find('.info').text('');
    Robot.initial();
  };
  addNumberToAllButtonClick = function(){
    var i$, ref$, len$;
    for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
      (fn$.call(this, ref$[i$]));
    }
    function fn$(btn){
      var this$ = this;
      $(btn).click(function(){
        if (btn.status === 'enable') {
          $(btn).find('.unread').removeClass('unseen');
          disableAllOtherButton(btn);
          btn.leave = pullRequerstToServerAndShowNumber(btn);
        }
      });
    }
  };
  disableAllOtherButton = function(btn){
    var i$, ref$, len$, button;
    for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
      button = ref$[i$];
      if (button !== btn && button.status !== 'done') {
        button.status = 'disabled';
        $(button).removeClass('enable').addClass('disabled');
      }
    }
  };
  pullRequerstToServerAndShowNumber = function(btn){
    return $.get('/' + Math.random(), function(number){
      $(btn).find('.unread').text(number);
      enableAllOtherButton(btn);
      calculate.add(number);
      if (allButtonIsDone()) {
        addResultToBubble();
      }
      Robot.clickNext();
    });
  };
  calculate = {
    sum: 0,
    add: function(number){
      return this.sum += +number;
    },
    reset: function(){
      this.sum = 0;
    }
  };
  enableAllOtherButton = function(btn){
    var i$, ref$, len$, button;
    for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
      button = ref$[i$];
      if (button !== btn && button.status !== 'done') {
        $(button).removeClass('disabled').addClass('enable');
        button.status = 'enable';
      }
    }
    $(btn).removeClass('enable').addClass('disabled');
    btn.status = 'done';
  };
  allButtonIsDone = function(){
    var i$, ref$, len$, btn;
    for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
      btn = ref$[i$];
      if (btn.status !== 'done') {
        return false;
      }
    }
    return true;
  };
  addResultToBubble = function(){
    $('#info-bar').removeClass('disabled').addClass('enable');
    $('#info-bar').click(function(){
      $('#info-bar').find('.info').text(calculate.sum);
    });
  };
  addResetToApbMouseleave = function(){
    $('#button').mouseleave(function(){
      var i$, ref$, len$, btn, ref1$;
      for (i$ = 0, len$ = (ref$ = $('.button')).length; i$ < len$; ++i$) {
        btn = ref$[i$];
        if ((ref1$ = btn.leave) != null) {
          ref1$.abort();
        }
      }
      return init();
    });
  };
  Robot = {
    initial: function(){
      this.btns = $('.button');
      this.cursor = 0;
    },
    clickNext: function(){
      if (this.cursor === this.btns.length) {
        return $('#info-bar').click();
      } else {
        return this.btns[this.cursor++].click();
      }
    }
  };
  addSequenceClickToApb = function(){
    $('.apb').click(function(){
      Robot.clickNext();
    });
  };
}).call(this);
